### PR TITLE
Use gulp-load-plugins

### LINKED ISSUE #37: Use gulp-load-plugins to decrease LOC in gulpfile.js

### PR DESCRIPTION
**Pull request by dciccale**
Fix #37

### CODE REVIEW

**Comment by dciccale** [comment]
basically all the long list of `var p = require('plugin')` was removed. now all plugins exists in `$` using camelCase like `$.minifyCss`

**Comment by delta98** [comment]
@dciccale I understand the importance of your PR, I'd like to encourage contributors to provide detailed requests and comments for others to understand what has taken place and why it's important. 

So thanks for taking the time to do so.

My only concern is increasing a barrier for other less informed developers. I think it serves a valid purpose, but I generally would like to keep it verbose, what do you think?

**Comment by dciccale** [comment]
it is a very well known way of writing your gulpfile,

plus the official material-design-lite uses it https://github.com/google/material-design-lite/blob/master/gulpfile.js

and many known projects, i think we should encourage good things outthere

**Comment by delta98** [comment]
Ok, agreed.

**Pull request merged**
